args: !!python/object:argparse.Namespace
  arch: attention
  att_dropout: 0.2
  batch_size: 32
  debug: false
  dropout_rate: 0.2
  early_stopping_patience: 100
  epochs: 20
  evaluate_every: 0.25
  gammas:
  - 0.6
  - 0.6
  hidden_dim:
  - 256
  lbda: 0.5
  learning_rate: 0.0001
  loss_type: bce
  min_lr: 1.0e-08
  momentum: 0.9
  n_layers: 6
  num_heads: 16
  optimizer: adamw
  pretrain_epochs: 10
  pretrained: null
  resume: null
  save: defender/att.pkl
  save_dir: ./saved_models
  save_every_epochs: 1
  seed: null
  skip_training: null
  steps_lr:
  - 4
  - 8
  tau: 10.0
  warmup_epochs: 1.0
  weight_decay: 0.0002
  workers: 12
features_dim:
- 22
- 77
- 11335
- 3541
num_batches: 7450
pos_samples: 116442
textual_idx:
- 2
- 3
- 4
- 5
- 6
- 7
use_features:
- 0
- 1
- 2
- 3
val_datasets: 14
