args: !!python/object:argparse.Namespace
  arch: attention
  att_dropout: 0.7
  batch_size: 32
  debug: false
  dropout_rate: 0.7
  early_stopping_patience: 100
  epochs: 10
  evaluate_every: 0.25
  gammas:
  - 0.9
  - 0.9
  hidden_dim:
  - 256
  lbda: 0.5
  learning_rate: 5.0e-06
  loss_type: bce
  momentum: 0.9
  n_layers: 12
  num_heads: 8
  optimizer: adamw
  resume: null
  save: defender/att_ember.pkl
  save_dir: ./saved_models
  save_every_epochs: 1
  seed: null
  skip_training: null
  tau: 10.0
  warmup_epochs: 0.5
  weight_decay: 0.0002
  workers: 12
features_dim:
- 77
- 570
- 2067
num_epochs: 1741
pos_samples: 9881
textual_idx:
- 2
- 3
- 4
- 5
- 6
- 7
use_features:
- 1
- 2
- 3
val_datasets: 14
